# Generated by Django 5.2.15 on 2026-06-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='subtitle',
            field=models.CharField(default='Enter subtitle', max_length=500),
            preserve_default=False,
        ),
    ]
